# Используем базовый образ PostgreSQL на Alpine Linux
FROM postgres:alpine

# Устанавливаем переменные окружения для PostgreSQL
ENV POSTGRES_DB=tb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=il

# Открываем порт для PostgreSQL
EXPOSE 5432

#docker build -t test_postgres .
 #docker run -d --name test_postgres -p 5432:5432 test_postgres
